### ISSUE TITLE
patched

### ISSUE THREAD

**Issue by vipkingo1** [Exunys/Anti-Kick#1]
its been patched

**Comment by Ezekiel-Game** [comment]
true

**Comment by Iinksafe** [comment]
false. DM me on discord for an undetected version @Ezekiel-Game @vipking-o1

**Comment by quanmanss11** [comment]
Read it before being goofy. https://github.com/Exunys/Anti-Kick/blob/main/README.md

**Comment by quanmanss11** [comment]
It means that the script can only bypass local script kicks (meaning that the server can still kick you, and local side kicks are like an alt for the leave button).

**Comment by quanmanss11** [comment]
If you still don't understand "local side kick" force you to press the "Leave" button (THIS IS JUST an EXAMPLE to make you understand what I'm trying to say)
